### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by loleg** [LucaKern/Save-the-Data---.docx-im-Jahre-2133#1]
It would be great if you could add a LICENSE.md file with an open source license for the results of the Hackdays. I recommend using MIT or Apache licenses, and you can use this tool to decide: https://choosealicense.com/

**Comment by LucaKern** [comment]
Thanks for you input Oleg. We will add a MIT licence.

**Comment by LucaKern** [comment]
done

**Comment by loleg** [comment]
thx!
